### ISSUE TITLE
Rendering outside Remake project

### ISSUE THREAD

**Issue by tushantin** [morevnaproject/remake#25]
This is more of a general inquiry, or feature request, rather than an "issue". In any case, I hope the developers are willing to consider this. 

Is there any way to allow projects to render outside of the Remake folder, and carry that render location "information" through syncing to multiple devices? Maybe by having the location specified in "remake.conf" file? 

If so, how do I set it? And if not, then are there any plans to implement such a feature in the future?

**Comment by morevnaproject** [comment]
Hi! We do not plan to implement rendering outside of the remake project. The render directory cannot be relocated into other place, because your project files reference the files form that directory. If each user will have it in different location, then there will be missing files and the project won’t rebuild correctly.

Though, you can use some workarounds mentioned here - http://morevnaproject.org/2013/07/21/remake-0-6-released/#comment-342344

For the synchronization workflows please see this post - http://morevnaproject.org/2013/08/27/synchronization-infrastructure-for-animation-projects/
